### ISSUE TITLE
Implement a general Matrix class

### ISSUE THREAD

**Issue by MaverickTse** [MaverickTse/MPUtl#6]
A class that holds the data pointer, and with members describing the underlying image data-structure.
The class should provide facilities to do shallow and deep copy. Create and initialize the matrix data whenever necessary.

This class will be further sub-classed into an Image Object and Audio Object

For design and implementation idea, refer to the OpenCV documentation on cv::Mat
http://docs.opencv.org/3.0.0/d3/d63/classcv_1_1Mat.html

**Comment by yumetodo** [comment]
I think that the behavior of  ``cv::Mat`` is Image Handl.

```cpp
cv:Mat img1;
cv:Mat img2;
cv:Mat img3;
//do something
img1 = img2;//shallow copy
img1 = std::move(img3);//shallow copy
img2 = img3.clone();//deep copy

std::vector<uint8_t> v1;
std::vector<uint8_t> v2;
std::vector<uint8_t> v3;
//do something
v1 = v2;//deep copy
v2 = std::move(v3);//move
```

Whitch behavior is prefer?A:as image handl(use std::shared_ptr-like class to manage allocated memory), B:as image(like std::vector/std::string).

Incidentally, in [DxLibEx project](https://github.com/Nagarei/DxLibEx/issues/4#issuecomment-152794366), we decided to delete copy constructor/copy assignment operator, and the behavir is

- shallow copy : unable
- deep copy : call ``clone`` member-function and move constructor/move assignment operator
- move : call move constructor/move assignment operator

**Comment by MaverickTse** [comment]
just a safe pointer should be enough. 
I may change my mind if actual implementation encounters problem :-P

**Comment by yumetodo** [comment]
How to guarantee the thread-safe?

**Comment by MaverickTse** [comment]
No guarantee for thread-safety by default. Since this is considered just as a convenient wrapper for raw matrix data.

**Comment by MaverickTse** [comment]
Done
（うPしないけど）
